Gilead-BioStats/gsm

- R/Country_Map_Raw.R
- inst/report/KRIReportByCountry.Rmd
`Country_Map_Raw` wasn't actually using its argument - my bad!
> Fix bug in `Country_Map_Raw`.

- .github/workflows/pkgdown.yaml
- R/Country_Map_Raw.R
- R/MakeAnalysisDate.R
- R/MakeResultsAnalysis.R
- R/MakeResultsBounds.R
- R/MakeResultsSummary.R
- R/MakeStatusWorkflow.R
- R/Study_Report.R
- R/Timeline.R
- R/util-UpdateLabels.R
- README.md
- inst/report/KRIReportByCountry.Rmd
- inst/report/KRIReportByQTL.Rmd
- man/Country_Map_Raw.Rd
- man/MakeAnalysisDate.Rd
- man/MakeResultsAnalysis.Rd
- man/MakeResultsBounds.Rd
- man/MakeResultsSummary.Rd
- man/MakeStatusWorkflow.Rd
- man/Make_Timeline.Rd
- man/Study_Report.Rd
- man/UpdateLabels.Rd
Minor readme updates, including fixing the broken links. Action still needs update described in issue. 
Notes:
> Update README.md. #1305

- R/Make_Snapshot.R
- man/Make_Snapshot.Rd
> removed bUpdateParams from Make_Snapshot

- R/Study_Report.R
- inst/report/KRIReportByCountry.Rmd
- inst/report/KRIReportByQTL.Rmd
- inst/report/KRIReportBySite.Rmd
- man/Study_Report.Rd
fix #1310 
Notes: 
I noticed an issue when trying to generate country and QTL reports which I addressed in this aswell
> fixed reporting bug for country and QTL and added reporting summary info

- R/Augment_Snapshot.R
- R/Overview_Table.R
- R/Study_Report.R
- R/Widget_TimeSeriesQTL.R
- inst/htmlwidgets/Widget_TimeSeriesQTL.js
- inst/report/KRIReportByCountry.Rmd
- inst/report/KRIReportByQTL.Rmd
- inst/report/KRIReportBySite.Rmd
> reopened for minor discrepancy

- R/Overview_Table.R
- R/Timeline.R
- R/util-ReportHelpers.R
- inst/report/KRIReportByCountry.Rmd
- inst/report/KRIReportByQTL.Rmd
- inst/report/KRIReportBySite.Rmd
- inst/utils-0.0.1/showMetaTableDetails.js
- man/MakeStudyStatusTable.Rd
- man/Make_Timeline.Rd
fix #1341 optional interactivity (done)
fix #1340 remove whitespace (done)
fix #1343 add snapshot to timeline (done)
fix #1342 fixed bug with study status js (done)
Notes:
> removed white space for timeline and added snapshot points and stats

- .github/workflows/pkgdown.yaml
Fix #1324 
- This should resolve the `pkgdown` build so that sample reports are sent to a custom drop-down without any manual steps.
- Tested with [this deployment](https://github.com/Gilead-BioStats/gsm/actions/runs/6436564210)
> Fix 1324 - update pkgdown YAML

- inst/specs/AE_Map_Raw.yaml
- tests/testthat/_snaps/AE_Map_Raw.md
- tests/testthat/_snaps/Study_Assess.md
> changed strTimeOnTreatmentCol to strTimeOnStudyCol

- inst/report/KRIReportByQTL.Rmd
fixed missing argument in QTL report
> Release v1.8.3 rc 2

- .github/workflows/pkgdown.yaml
Patch fix to deploy `pkgdown` site.
> Fix pkgdown

- R/AE_Assess.R
- R/Consent_Assess.R
- R/DataChg_Assess.R
- R/DataEntry_Assess.R
- R/Disp_Assess.R
- R/IE_Assess.R
- R/LB_Assess.R
- R/MakeKRICharts.R
- R/PD_Assess_Binary.R
- R/PD_Assess_Rate.R
- R/QueryAge_Assess.R
- R/QueryRate_Assess.R
- R/Screening_Assess.R
- R/util-RunStratifiedWorkflow.R
- tests/testthat/_snaps/Consent_Assess.md
- tests/testthat/_snaps/DataChg_Assess.md
- tests/testthat/_snaps/DataEntry_Assess.md
- tests/testthat/_snaps/Disp_Assess.md
- tests/testthat/_snaps/IE_Assess.md
- tests/testthat/_snaps/LB_Assess.md
- tests/testthat/_snaps/PD_Assess_Binary.md
- tests/testthat/_snaps/PD_Assess_Rate.md
- tests/testthat/_snaps/QueryAge_Assess.md
- tests/testthat/_snaps/QueryRate_Assess.md
- tests/testthat/_snaps/Screening_Assess.md
- tests/testthat/test_util_ConsolidateStrata.R
Just a slight tweak to workflow. Not critical. 
Notes:
> minor workflow tweak

- vignettes/v1_9_0-data-model-update-reference.Rmd
fix #1430 
create vignette highlighting changes between gsm v1.8.0 and v1.9.0
Notes:
> created vignette template

- DESCRIPTION
- man/Study_Report.Rd
Hotfix for version in `DESCRIPTION` file only.
> new rc branch for DESCRIPTION file

- vignettes/articles/Qualification.Rmd
> Fix 1463 - uncomment test coverage section in qualification report

- inst/report/KRIReportByCountry.Rmd
- inst/report/KRIReportByQTL.Rmd
- inst/report/KRIReportBySite.Rmd
Fix #1467 
Hoping that this easy change will suppress the warnings/messages.
> Fix `Timeline()` warnings during report generation

- inst/report/KRIReportByCountry.Rmd
- inst/report/KRIReportByQTL.Rmd
- inst/report/KRIReportBySite.Rmd
fix #1481
added logic to allow for report rendering in local RStudio
Notes:
> added logic to use reports in local RStudio

- R/Widget_BarChart.R
- R/Widget_ScatterPlot.R
- R/Widget_TimeSeries.R
- inst/htmlwidgets/Widget_BarChart.js
- inst/htmlwidgets/Widget_ScatterPlot.js
- inst/htmlwidgets/Widget_TimeSeries.js
- inst/utils-0.0.1/addSiteSelect.js
- man/Analyze_Fisher.Rd
- man/IE_Map_Raw.Rd
- man/Make_Timeline.Rd
- man/PD_Assess_Binary.Rd
- man/PD_Map_Raw_Binary.Rd
- man/PD_Map_Raw_Rate.Rd
- man/RunQTL.Rd
- man/Widget_BarChart.Rd
- man/Widget_ScatterPlot.Rd
Fix #1497
Use data created in [this PR](https://github.com/Gilead-BioStats/gsmApp/pull/68) to test app functionality.
Quick test for Widgets:
```
snapshot <- Make_Snapshot()
Study_Report(snapshot)
```
Notes:
> Fix 1497 - update widgets for use in `gsmApp`

- R/Covariate_Chart.R
- man/Covariate_Chart.Rd
- man/Covariate_Map.Rd
- man/covariate_chart_site.Rd
- man/covariate_chart_study.Rd
> add chart functions

- inst/workflow/kri0001.yaml
- inst/workflow/kri0002.yaml
- inst/workflow/kri0003.yaml
- inst/workflow/kri0004.yaml
- inst/workflow/kri0005.yaml
- inst/workflow/kri0006.yaml
- inst/workflow/kri0007.yaml
- inst/workflow/kri0008.yaml
- inst/workflow/kri0009.yaml
- inst/workflow/kri0010.yaml
- inst/workflow/kri0011.yaml
- inst/workflow/kri0012.yaml
Added vThreshold to meta in workflow. 
@lauramaxwell can you apply to other workflows? 
Only difference from test code in #1545 is that `dfMetrics` is derived as follows: 
```
dfMetrics <- wf_metrics %>% map_df(function(wf){
wf$meta$vThreshold <- paste(wf$meta$vThreshold, collapse = ",")
return(wf$meta)
})
```
Full updated script is: 
```
devtools::load_all()
wf_mapping <- MakeWorkflowList(strNames="mapping")[[1]]
wf_metrics <- MakeWorkflowList(strNames=paste0("kri",sprintf("%04d", 1:12)))
dfMetrics <- wf_metrics %>% map_df(function(wf){
wf$meta$vThreshold <- paste(wf$meta$vThreshold, collapse = ",")
return(wf$meta)
})
dfStudy<-clindata::ctms_study %>% rename(StudyID = protocol_number)
dfSite<- clindata::ctms_site %>% rename(SiteID = site_num)
lRaw <- gsm::UseClindata(
list(
"dfSUBJ" = …
```
> add vThreshold in meta. fix #1542

- R/Report_Setup.R
- inst/report/Report_KRI.Rmd
- man/Report_OverviewText.Rd
- man/Report_Setup.Rd
Bugfix for proper df specification for KRI_Report helper functions
closes #1547 
test file for `KRI_Report.R`
```
lCharts <- list(
kri0001 = NULL
)
dfSummary <- tibble::tibble(
GroupID = c("10", "100", "101", "102", "103"),
GroupType = rep("Site", 5),
Numerator = seq(2,10,2),
Denomicator = seq(10,50,10),
Metric = c(0.02, 0.02, 0.02, 0.02, 0.02),
Score = c(1,3,2,1,1),
Flag = c(0,2,1,0,0),
MetricID = rep("kri0001", 5)
)
dfStudy <- clindata::ctms_study %>% rename(StudyID = protocol_number)
dfSite <- clindata::ctms_site %>% rename(SiteID = site_num)
dfMetrics <- tibble::tibble(
metric = "Adverse Event Rate",
workflowid = "kri0001",
group = "Site"
)
test_that("Check default output path when strOutpath is NULL", {
expect_output(
Report_KRI(lCharts = lCharts, dfSummary = dfSummary, dfStudy = …
```
> fix: KRI reporting bugs

- inst/workflow/counts.yaml
New yaml workflow to add participants and sites counts for the at study- and site-level. 
```
wf <- yaml::read_yaml('./inst/workflow/counts.yaml')
lData <- list(dfEnrolled = clindata::rawplus_dm %>% filter(enrollyn == 'Y'))
results <- gsm::RunWorkflow(lWorkflow=wf, lData=lData)
results$lData$dfCounts
```
Notes:
> add counts workflow

- R/Analyze_QTL.R
- R/Flag_QTL.R
- R/Visualize_QTL.R
- man/Analyze_QTL.Rd
- man/Flag_QTL.Rd
- man/Input_Rate.Rd
- man/Report_MetricTable.Rd
- man/Visualize_QTL.Rd
Marks all `_QTL` functions as experimental
closes #1553 
Notes:
> Mark all `QTL` functions as experimental

- R/Input_Rate.R
- R/Widget_SiteOverview.R
- tests/testthat/test_Input_Rate.R
change `Rate` column to `Metric` in output of `Input_Rate()` to match other data.frames in analytics data model
closes #1608 
Notes:
> Update Input_Rate output

- R/Widget_SiteOverview.R
- tests/testthat/test-Widget_SiteOverview.R
- tests/testthat/testdata/create_simple_data.R
- Make each test self-contained.
- Use new data structure.
- Disable the elementId test (pending discussion).
Closes #1617.
> Update Widget_SiteOverview tests.

- R/RunWorkflows.R
- R/Visualize_Metric.R
- R/util-BindResults.R
- R/util-MakeGroupInfo.R
- R/util-MakeMetricInfo.R
- man/BindResults.Rd
- man/MakeGroupInfo.Rd
- man/MakeMetricInfo.Rd
- man/RunWorkflows.Rd
- man/Visualize_Metric.Rd
- tests/testthat/_snaps/ParseThreshold.md
- tests/testthat/_snaps/util-MakeWorkflowList.md
- tests/testthat/_snaps/util_MakeAssessmentList.md
- tests/testthat/test_ParseThreshold.R
- tests/testthat/test_Widget_BarChart.R
- tests/testthat/test_Widget_ScatterPlot.R
- tests/testthat/test_util-MakeWorkflowList.R
- tests/testthat/test_util-RunWorkflow.R
- vignettes/DataAnalysis.Rmd
Fixed tests for widgets and workflow helper functions
closes #1620 
closes #1556 
Fixed examples and documentation for R CMD checks to pass
closes #1622 
closes #1623 
Notes: 
Not quite there, but getting closer to having checks pass per #1611 
When reporting workflow is complete, tests will need to be revisited for coverage and pkgdown site construction can be addressed.
> Fix tests, examples and documentation for checks

- R/RunWorkflows.R
- R/util-BindResults.R
- R/util-MakeCharts.R
- R/util-MakeLongMeta.R
- R/util-MakeMetric.R
- R/util-MakeWideGroups.R
- man/BindResults.Rd
- man/MakeCharts.Rd
- man/MakeLongMeta.Rd
- man/MakeMetric.Rd
- man/MakeWideGroups.Rd
- man/RunWorkflows.Rd
- tests/testthat/_snaps/util-MakeCharts.md
- tests/testthat/test-util-BindResults.R
- tests/testthat/test-util-MakeCharts.R
- tests/testthat/test-util-MakeLongMeta.R
- tests/testthat/test-util-MakeMetric.R
- tests/testthat/test-util-MakeWideGroups.R
Add unit tests for util files:
Notes:
> Add util tests

- README.md
> Added gsm article links to ReadMe

- .github/workflows/qualification-report.yaml
>  Fix qualification report workflow

- .github/workflows/test-coverage.yaml
Use modern versions of the coverage setup.
This does not report results to codecov, but it still closes #1634.
Notes:
> Standardize/clean test-coverage.yaml.

- .github/workflows/R-CMD-check-dev.yaml
- .github/workflows/R-CMD-check-main.yaml
- .github/workflows/pkgdown-dev.yaml
- .github/workflows/pkgdown-pr.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/qualification-report.yaml
- .github/workflows/qualification-tests-dev.yaml
- .github/workflows/test-coverage.yaml
- Simplify R-CMD-check-dev matrix.
- Remove unused (I think, checks will verify) ssh-agent step from all GHA workflows.
Notes: 
Closes #1737
> Simplify `R-CMD-check-dev.yaml` matrix

- .github/workflows/pkgdown-dev.yaml
- .github/workflows/qualification-report.yaml
- NEWS.md
ensures latest version of the qualification report is saved in the release.
closes #1747
Notes:
> Update `qualification_report.yaml` to overwrite report if necessary

- R/Input_Rate.R
- R/RunWorkflows.R
- man/Input_Rate.Rd
nitpicks as I go through the gsm codebase working my way backwards from the vignette code
> some misc code review cleanup/fixups as I go through the RC

- .github/workflows/pkgdown-dev2main.yaml
- .github/workflows/pkgdown.yaml
Add a GHA to build the FULL site on PR to main, so we can make sure sample reports work.
Closes #1640
Notes: 
Do NOT merge this. I'm temporarily building sample reports on every PR to dev with this, but I think at most we want to do this on PR to main, merge to main, and MAYBE merge to dev.
> Build sample reports.

- R/Report_StudyInfo.R
Undo an incorrect "fix".
Closes #1802
Notes:
> Report_StudyInfo: Show/Hide

- R/Widget_ScatterPlot.R
- inst/htmlwidgets/Widget_ScatterPlot.js
- man/Widget_ScatterPlot.Rd
Adds code for footnote at the bottom of scatterplot to indicate size of points is relative to size of group
- Closes #1728
> Closes #1728 Adds footnote to scatterplot widget

- inst/workflow/1_mappings/ENROLL.yaml
- tests/testqualification/qualification/qual_workflows/1_mappings/ENROLL.yaml
change ENROLL.yaml field from "yes" to "true" for consistency
fix error in meta example in gsm Extensions vignette
- Closes #XXX
> yes to true in yamls

- DESCRIPTION
- R/util-MakeWorkflowList.R
- _pkgdown.yml
- pkgdown dropdown navbar needed aesthetic fixing
- Zelos' email was appearing as a middle name
- `MakeWorkflowlist()` which is run recursively in `3_reporting/Metrics.yaml` was giving errors related to file name and ID not matching
> Closes  #1872 fix miscellaneous aesthetics things and issues

- R/Report_MetricTable.R
- R/Visualize_Metric.R
- R/util-MakeStudyInfo.R
- Closes #1886 
- Closes #1887 
- Closes #1888
> Resolve errors related to missing data and an incomplete set of `MetricID` in `dfBounds`.

- inst/report/lib/overallGroupDropdown.js
Resolves bug in overall group select in report.
- Closes #1902
> Fix overall group select bug.

- R/Report_MetricTable.R
- R/util-Report.R
> avoid column name conflicts between `Groups` and `Results`

- inst/report/toggleButton.css
Don't change the background color when the switch flips to "Hide Details".
`htmltools::html_print(Report_StudyInfo(reportingGroups))` is the easiest way to see it.
- Closes #1916.
> Keep bg color for switch.

- DESCRIPTION
- R/Report_Setup.R
- R/RunQuery.R
- R/util-ApplySpec.R
- inst/report/Report_KRI.Rmd
- man/RunQuery.Rd
- tests/testthat/test-Report_Setup.R
Adds nickname to report header (when present) and fixes a bug that caused errors in RunQuery Dates outside of `ApplySpec()`
Run example 3.2 in `inst/examples/3_ReportingWorkflow.R`
- Closes #1878
- Closes #1914
> Add Nickname to report header and fix `RunQuery` bug

- DESCRIPTION
- NEWS.md
- R/Report_MetricTable.R
- R/Report_Setup.R
- R/Report_StudyInfo.R
- R/Widget_FlagOverTime.R
- R/util-ApplySpec.R
- R/util-CalculatePercentage.R
- R/util-Report.R
- inst/workflow/1_mappings/STUDY.yaml
- inst/workflow/2_metrics/cou0004.yaml
- inst/workflow/2_metrics/kri0004.yaml
- tests/testthat/_snaps/Report_StudyInfo.md
- tests/testthat/_snaps/util-MakeWorkflowList.md
- tests/testthat/test-Report_Setup.R
This patch release primarily addresses minor report updates and handling classes in sql queries properly. Specifically:
- Add method param to RunQuery so that we can use `"name__class"` method
- update Flags Over Time widget to only show past 12 months by default, but add toggle to show full history
- display site/participant target as `n/N (x%)` in reports
- display study nickname on report (if present)
- use `gt` for tables throughout entire package
- Closes #XXX
> gsm v2.1.2 release candidate

- inst/workflow/2_metrics/cou0007.yaml
- inst/workflow/2_metrics/kri0007.yaml
- tests/testthat/_snaps/util-MakeWorkflowList.md
update the query per #1959 
- Closes #1959
> Update query for treatment discontinuation KRIs

- inst/workflow/1_mappings/STUDY.yaml
- tests/testthat/_snaps/util-MakeWorkflowList.md
> Fix typo in STUDY.yaml

- R/RunQuery.R
- tests/testthat/test_RunQuery.R
> run styler on 2.2 

- DESCRIPTION
- README.md
Fixes bug in readme that links to incorrect reports. bunp version to 2.2.0.9999 for dev
- Closes #1993
> update readme report links and dev version

- R/zzz.R
- README.md
Added a notice upon loading in  `.onAttach` as well as at the top of the README to inform the user of the replacement of gsm with a set of modularized packages.
- Closes #XXX
> gsm deprecation messages
