Gilead-BioStats/gsm

R/Overview_Table.R

Fix #1288 
- Returns a blank value for <<group>> count if it is not located in the `dfSITE` dataset
- This allows the user to review the report and correct missing data if needed, without the report throwing an error

Fix #1288 - Missing values in `dfSITE`

---

_pkgdown.yml

Hotfix release to address `pkgdown` site from failing. 
I believe this is because the `/docs/` folder, which is `.gitignore`d, has standard folders where assets are kept. I can't find any documentation that supports a custom directory, so I am *hoping* that this fix resolves the issue of reports being 404'd.

Release v1.8.1-rc2

---

R/Augment_Snapshot.R
R/util-ExtractDirectoryPaths.R
R/util-StackSnapshots.R

Adding to changes in #1347, this PR adds logic to exit `stackSnapshots()`/`Augment_Snapshot()` if a dated folder is not found and/or if the user attempts to run `Augment_Snapshot()` on a single snapshot. 
- `stackSnapshots()` returns `NULL` if folder is not found.
- `Augment_Snapshot()` returns `NULL` if `stackSnapshots()` returns `NULL`.

Fix 1347 tweak

---

R/Widget_TimeSeries.R
inst/htmlwidgets/Widget_TimeSeries.js

Fix #1490 
JS for click event was trying to select an ID that was being duplicated because of missing `unique()` wrapper.
To test:
- Create longitudinal snapshot
- Click on a scatter plot point in the timeseries chart and confirm that a trend line appears and that the drop-down element is updated correctly.
```r
snap_one <- Make_Snapshot(strAnalysisDate = "2022-01-01")
snap_two <- Make_Snapshot(strAnalysisDate = "2022-02-01", lPrevSnapshot = snap_one)
snap_two$lCharts$kri0001$timeSeriesContinuousJS
```
For reference, the bug can be seen on [`pkgdown`](https://gilead-biostats.github.io/gsm/StandardReportSite.html#_AE_Reporting_Rate_5)

fix bug for clickevent on timeseries chart

---

R/MakeKRICharts.R
R/Widget_TimeSeries.R
R/util-ReportHelpers.R
man/Widget_TimeSeries.Rd
tests/testthat/_snaps/Study_Map_Raw.md
tests/testthat/test_Study_Map_Raw.R
tests/testthat/test_Widget_TimeSeries.R

This was for fix #1508.
I modified `Widget_TimeSeries.R` to include a new parameter (`yAxis`). This parameter allows the user to select a column from `lLabels`, such as `metric`, `score`, or `numerator`, to be used in the creation of the data viz widget.
The default param option is `score`. When this default is changed, `lParams` is turned into a NULL value when passed to the widget.
Some other files I modified include:
* `MakeKRICharts.R` to generate the two additional data visualizations when `Make_Snapshot()` is executed
* `MakeReportsTable.R` to generate the two additional tabs when `Study_Report()` is executed
```
data <- list(
dfSUBJ = clindata::rawplus_dm,
dfAE = clindata::rawplus_ae,
dfPD = clindata::ctms_protdev,
dfSTUDCOMP = clindata::rawplus_studcomp,
dfSDRGCOMP = …
```

#1508: Adding two additional timeseries.

---

R/Report_FormatFlag.R
tests/testthat/test-Report_FormatFlag.R

Fixed typo in Report_FormatFlag() that was causing it to show negatives as positive and to not format positives.
Closes #1713
Notes:

Format flags properly with Report_FormatFlag.

---

.github/workflows/pkgdown-dev.yaml

Despite what I said in #1734, this doesn't appear to be triggered specifically because of the dev-to-main PR; it just looked like it because that PR "changes" whenever something merges into dev. What's really happening here is that there was a typo, which was causing this workflow to never actually (successfully) run (except once or twice early on when I was testing things).
Closes #1734.
Notes:

Fix workflow typo.

---

inst/report/Report_KRI.Rmd

Otherwise the report errors with Object MetricID not found, when run in a more isolated context where dplyr has not already been loaded already

fixup: add dplyr filter namespace

---

R/Report_MetricTable.R
R/Visualize_Metric.R
R/util-Report.R
inst/report/Report_KRI.Rmd
man/Report_MetricTable.Rd
man/Visualize_Metric.Rd
man/glossary/dfResults_filtered.Rmd
tests/testthat/test-Report_MetricTable.R
tests/testthat/test-Visualize_Metric.R
vignettes/DataReporting.Rmd

Resolves the bug in #1765 that tables were not rendering in report output.
Also adds the output of `Report_MetricTable()` to the `MakeCharts()`/`Visualize_Metric()` output as `metricTable` for easier reference in report generation.  
Updated relevant documentation to note the addition of `metricTable` to `lCharts` list.
closes #1765
```
lCharts <- MakeCharts(
dfResults = reportingResults,
dfGroups = reportingGroups,
dfMetrics = reportingMetrics,
dfBounds = reportingBounds
)
lCharts$kri0001$metricTable
strOutpath <- "StandardSiteReport.html"
Report_KRI(
lCharts = lCharts,
dfResults = reportingResults,
dfGroups = reportingGroups,
dfMetrics = reportingMetrics,
strOutpath = strOutpath
)
```
Notes:

Fix summary tables in reports and add `metricTable` to `Visualize_Metric()` output

---

R/util-checkSpec.R
inst/workflow/metrics/kri0001.yaml
inst/workflow/metrics/kri0002.yaml
tests/testthat/test-util-checkSpec.R

closes #1777
```
lData <- list(reporting_groups = gsm::reportingGroups)
lSpec <- list(
reporting_groups = list(
GroupID = list(required = TRUE),
GroupLevel = list(required = TRUE),
Param = list(required = TRUE),
Value = list(required = TRUE),
NewVar = list(required = FALSE)
)
)
CheckSpec(lData, lSpec) # Prints message that everything is found
lSpec <- list(
reporting_groups = list(
GroupID = list(required = TRUE),
GroupLevel = list(required = TRUE),
Param = list(required = TRUE),
Value = list(required = TRUE),
NewVar = list(required = TRUE)
)
)
CheckSpec(lData, lSpec) # Returns error that NewVar is not found
```
Notes:

Use `required` param from `spec` in `CheckSpec()`

---

inst/workflow/metrics/cou0001.yaml
inst/workflow/metrics/cou0002.yaml
inst/workflow/metrics/cou0003.yaml
inst/workflow/metrics/cou0004.yaml
inst/workflow/metrics/cou0005.yaml
inst/workflow/metrics/cou0006.yaml
inst/workflow/metrics/cou0007.yaml
inst/workflow/metrics/cou0008.yaml
inst/workflow/metrics/cou0009.yaml
inst/workflow/metrics/cou0010.yaml
inst/workflow/metrics/cou0011.yaml
inst/workflow/metrics/cou0012.yaml
inst/workflow/metrics/kri0001.yaml
inst/workflow/metrics/kri0002.yaml
inst/workflow/metrics/kri0003.yaml
inst/workflow/metrics/kri0004.yaml
inst/workflow/metrics/kri0005.yaml
inst/workflow/metrics/kri0006.yaml
inst/workflow/metrics/kri0007.yaml
inst/workflow/metrics/kri0008.yaml
inst/workflow/metrics/kri0009.yaml
inst/workflow/metrics/kri0010.yaml
inst/workflow/metrics/kri0011.yaml
inst/workflow/metrics/kri0012.yaml
tests/testthat/_snaps/util-MakeWorkflowList.md

Updated `spec`s in `inst/metrics` yamls to include:
- `type` field to allow for validation in `CheckSpec()`
- all columns needed to perform queries in the workflow.
closes #1778
closes #1807 
Notes:

Add `type` field and query columns to all `spec`s

---

R/util-checkSpec.R
tests/testthat/test-util-checkSpec.R

Added a simple type validation to `CheckSpec()` to ensure the data is coming in in the correct format based on optional `type` field in `spec`. Also added test to ensure we get an error message when there is a format mismatch
closes #1810 
Notes:

Add type validation to `CheckSpec()`

---

R/Report_StudyInfo.R
tests/testthat/test-Report_StudyInfo.R

- Use of `slice(1:5)` contributed to indiscriminant first five attributes
- To fix, need to find some sort of logic that grabs: protocol id, nickname, and site/participant numbers
- Took a look at the `testthat` file that corresponded to `Report_StudyInfo()` to grab what looked like controlled terminology/standard convention names
Notes:

Closes #1722 Study Status Table display bugfix of indiscriminant first five attributes

---

R/Widget_BarChart.R
R/Widget_FlagOverTime.R
R/Widget_GroupOverview.R
R/Widget_ScatterPlot.R
R/Widget_TimeSeries.R
tests/testthat/test-Widget_FlagOverTime.R
tests/testthat/test-Widget_GroupOverview.R
tests/testthat/test_Widget_BarChart.R
tests/testthat/test_Widget_ScatterPlot.R
tests/testthat/test_Widget_TimeSeries.R

- `stopifnot()` chunk was added at the beginning of each widget app
- Closes #1795

Closes #1795 add assertions/stopifnot for widget inputs

---

R/RunStep.R
R/RunWorkflow.R
R/RunWorkflows.R
R/util-BindResults.R
inst/workflow/1_ingest.yaml
inst/workflow/2_map.yaml
inst/workflow/3_analyze.yaml
inst/workflow/4_reporting.yaml
inst/workflow/5_modules.yaml
inst/workflow/modules/report_kri_country.yaml

Updates the `analyze` workflow to run on the output of the `map` workflow. The intent is to allow each of the numbered workflows to run on the output of the previous workflow without any additional variables. One design principle that I'm following is each input to the mapped, analysis, and reporting layers should correspond to a data frame rather than a list of data frames, to align with a database and/or flat file data model.
```
load_all()
lSourceData <- list(
Source_STUDY = clindata::ctms_study,
Source_SITE = clindata::ctms_site,
Source_SUBJ = clindata::rawplus_dm,
Source_AE = clindata::rawplus_ae,
Source_PD = clindata::ctms_protdev,
Source_LB = clindata::rawplus_lb,
Source_STUDCOMP = clindata::rawplus_studcomp,
Source_SDRGCOMP = clindata::rawplus_sdrgcomp,
Source_QUERY = …
```

make analysis workflow work

---

R/util-checkSpec.R
tests/testthat/test-util-checkSpec.R

Adds new message option to handle when all data tables in the spec have `_all` required.
New test added to ensure this message is displayed in proper circumstance
- Closes #1845

Update `checkSpec()` cli message to handle `_all` required

---

R/Input_Rate.R
tests/testthat/test-Input_Rate.R

Address function/bugs such that it works "as expected"
Add new error messaging for all 0 denominator entry (would cause x/0 NaN on all metric value)
- Closes #1897

Closes #1894 address bug in `Input_Rate()` for 0 row dataframe inputs for dfNumerator/dfDenominator

---

R/Report_MetricTable.R
R/Report_OverviewText.R
R/Report_Setup.R
tests/testthat/_snaps/Report_MetricTable.md
tests/testthat/test-Report_MetricTable.R
tests/testthat/test-Report_OverviewText.R

Update Report_OverviewText and Report_Setup to handle country overview text properly. also deals with two existing bugs that displayed only red flag counts in the description and calculated `no_alert_groups` incorrectly.
Previous text:
Updated text:
- Closes #XXX

Fix country overview text

---

R/RunQuery.R
R/util-ApplySpec.R

added `method = "name__class"` to `sqldf` in `RunQuery` and adjusted `ApplySpec` to account for adjustment
- Closes #1912

updated class structure

---

R/util-ApplySpec.R
R/util-CombineSpecs.R
R/util-Ingest.R
man/Ingest.Rd
tests/testthat/test-util-CombineSpecs.R
tests/testthat/test-util-Ingest.R

Fix Ingest return value (spotted by actually using the docs 😊).
Update `CombineSpecs()` to better handle non-required columns.
Added tests to make sure this doesn't regress.
- Closes #1924

Fix Ingest return value

---

inst/examples/3_ReportingWorkflow.R
inst/workflow/3_reporting/Metrics.yaml
tests/testthat/_snaps/util-MakeWorkflowList.md

`lWorkflows` should be based on the current module/study being run, not always just the `gsm` workflows. This simply updates the flow to take an `lWorkflows` argument in the `lData` list in `RunWorkflows()` to run Metrics.yaml properly. 
Note: `lWorkflows` was already being fed into `RunWorkflows()` in this way, so this is not an update to process, just a simplification.
- Closes #1929

Update `Metrics.yaml` to not generate `lWorkflows` within steps

---

inst/report/Report_KRI.Rmd

Try "removing" kri0001 and cou0001 from the analysis data in example 3.1
```
reporting_wf <- MakeWorkflowList(strPath = "workflow/3_reporting")
reporting <- RunWorkflows(reporting_wf, c(mapped, list(lAnalyzed = analyzed[-c(1,13)],
lWorkflows = metrics_wf)))
```

Closes #1937 Display only results of metrics where data is available in reports

---

R/RunWorkflow.R
R/RunWorkflows.R
inst/examples/4_WorkflowIO.R
man/RunWorkflow.Rd
man/RunWorkflows.Rd
tests/testthat/test-RunWorkflow.R

Adds a `LoadData` hook at the beginning of `RunWorkflow` and a `SaveData` hook at the end.
Simplest use case that hits `clindata` and writes to .csv, also captured in `inst/examples/WorkflowIO.R`:
```
load_all()
LoadData <- function(lWorkflow, lConfig) {
purrr::imap(
lWorkflow$spec,
~ {
input <- lConfig$Domains[[ .y ]]
if (is.data.frame(input)) {
data <- input
} else if (is.function(input)) {
data <- input()
} else if (is.character(input)) {
data <- read.csv(input)
} else {
cli::cli_abort("Invalid data source: {input}.")
}
return(ApplySpec(data, .x))
}
)
}
SaveData <- function(lWorkflow, lConfig) {
domain <- paste0(lWorkflow$meta$Type, '_', lWorkflow$meta$ID)
cli::cli_alert_info(domain)
if (exists(domain, lConfig$Domains)) {
output <- lConfig$Domains[[ domain ]] …
```

Add hooks to `RunWorkflow`.

---

R/Visualize_Metric.R

add `vThreshold` argument back into `Widget_BarChart()` call in `Visualize_Metric()`
see below: 
- Closes #1958

Add thresholds back into barcharts

---

R/RunWorkflow.R
inst/examples/4_WorkflowIO.R
man/RunWorkflow.Rd
tests/testthat/test-RunWorkflow.R

Prior behavior:
New behavior:
runs through to completion:

fix ldata passthrough, resolves #1981

---

R/RunQuery.R
tests/testthat/test_RunQuery.R

An issue popped up running the `Groups` workflow where `RunQuery` couldn't find a `type` attribute on a column spec.  This PR enforces the column spec data structure.
```
df <- data.frame(
Name = c("John", "Jane", "Bob")
)
lColumnMapping <- list(
emaN = list(
source = 'Name'
)
)
query <- "SELECT Name as emaN FROM df WHERE Name LIKE '%o%'"
expect_no_error(result <- RunQuery(query, df, bUseSchema = T, lColumnMapping = lColumnMapping))
expect_equal(class(result$emaN), "character")
```
- Closes #XXX

fix issue in `RunQuery` related to incomplete column spec

---

R/util-func-namespace.R
man/GetStrFunctionIfNamespaced.Rd

Simple fix to always have the same output class (function) in the `GetStrFunctionInNamespace()`
- Closes #1992

Fix #1992- always return function in namespace util

---

R/Report_StudyInfo.R
inst/examples/3_ReportingWorkflow.R
inst/workflow/1_mappings/COUNTRY.yaml
inst/workflow/1_mappings/SITE.yaml
inst/workflow/1_mappings/STUDY.yaml
inst/workflow/1_mappings/SUBJ.yaml
tests/testthat/_snaps/Report_StudyInfo.md
tests/testthat/_snaps/util-MakeWorkflowList.md
tests/testthat/test-RunWorkflow.R
vignettes/DataReporting.Rmd

This branch adds subject-level status using the study completion domain, then aggregates at the study, site, and country levels.
```
lSourceData <- list(
Raw_STUDY = clindata::ctms_study,
Raw_SITE = clindata::ctms_site,
Raw_SUBJ = clindata::rawplus_dm,
Raw_STUDCOMP = clindata::rawplus_studcomp
)
lWorkflows <- MakeWorkflowList(c('STUDY', 'SITE', 'COUNTRY', 'SUBJ', 'STUDCOMP'))
lSpec <- CombineSpecs(lWorkflows)
lRawData <- Ingest(lSourceData, lSpec)
lMappedData <- RunWorkflows(
lWorkflows,
lRawData
)
dfGroups <- RunWorkflow(
MakeWorkflowList('Groups')[[1]],
lMappedData
)
dfGroups %>% filter(Param == 'ActiveParticipants')
```
- Closes #2003

add subject disposition

---

DESCRIPTION
NEWS.md
R/Analyze_NormalApprox.R
R/Flag.R
R/Report_FormatFlag.R
R/Summarize.R
R/Visualize_Score.R
R/Widget_FlagOverTime.R
R/Widget_GroupOverview.R
R/Widget_ScatterPlot.R
R/Widget_TimeSeries.R
R/util-CalculatePercentage.R
R/util-Ingest.R
R/util-MakeBounds.R
R/util-MakeWorkflowList.R
R/util-Report.R
man/CalculatePercentage.Rd
tests/testthat/test-Flag.R
tests/testthat/test-RunWorkflow.R
tests/testthat/test-util-Report.R
vignettes/DataReporting.Rmd

Worked through [release checklist](https://gilead-biostats.github.io/gsm/articles/ContributorGuidelines.html#release-branch-workflow), and ready for review! 
This patch release primarily addresses minor report updates bug fixes. Specifically:
- Reduce size of flags over time table by only displaying the most recent 12 periods
- Return an object of class `function` from `GetStrFunctionIfNamespaced()`
- Generalize all `Flag_*` functions to a single `Flag()` function
- Use `log4r` framework set up in v2.2.0 for `stopif()`/`stopifnot()` calls
- Add Subject Disposition field to Study Completion domain
- Closes #XXX

gsm v2.2.1 release candidate

---

R/Analyze_NormalApprox.R
inst/examples/3_ReportingWorkflow.R
inst/report/Report_KRI.Rmd
inst/report/lib/toggleTOC.js
inst/report/styles.css

Per CM team request, adding a hamburger button to allow the user to hide the table of contents in the kri report. 
We might want to think about adjusting the default width of the report to be a percentage of the screen instead of a fixed width, but not sure if that is needed at the moment.
- Closes #1963

Add button to show/hide report table of contents
